name: CI

on:
  pull_request:
    branches:
      - "**"
  # Restricting this to master prevents the push-triggered workflow
  # from running on pull requests based on branches in this repository
  # (we only want pull_request-triggered workflow there).
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn ci
